INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 01', 'beneficente@gmail.com', 	null, null, 'Evento Beneficente', 	'Sorocaba - SP', 	'2020-04-05', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 02', 'devs.event@outlook.com', 	null, null, 'Evento dos Devs', 		'São Paulo - SP', 	'2020-06-08', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 03', 'front.event@facens.br', 	null, null, 'Evento de Front-end', 	'Curitiba - PR', 	'2020-09-07', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 04', 'back.event@facens.br', 	null, null, 'Evento de Back-end', 	'Curitiba - PR', 	'2020-09-17', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 05', 'saude.event@host.com.br', 	null, null, 'Evento de Hospitalar', 'São Paulo - SP', 	'2020-11-17', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 07', 'games.event@liga.br', 		null, null, 'Evento Games do Ano', 	'Brasília - DF', 	'2020-12-20', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 08', 'melhores.event@yahoo.br', 	null, null, 'Evento América Latina','Lindóia - RJ', 	'2020-11-30', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 09', 'cidade.sr.event@pref.br', 	null, null, 'Evento de São Roque', 	'São Roque - SP', 	'2020-06-15', null);
INSERT INTO tb_event (description, email_contact, end_date, end_time, name, place, start_date, start_time) VALUES ('Evento 10', 'graficasbr@hotmail.com', 	null, null, 'Evento das Gráficas', 	'Embu - SP', 		'2020-12-22', null);
